version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.11.0

    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Linter
          command: flake8
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t $DOCKER_IMAGE:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_IMAGE:$TAG
    
  deploy: # this can be any name you choose
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy on heroku
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SECRET_KEY=${SECRET_KEY} -a ${HEROKU_APP_NAME}
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set SENTRY_DSN=${SENTRY_DSN} -a ${HEROKU_APP_NAME}
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set MODE=${MODE} -a ${HEROKU_APP_NAME}
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web


workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker_image:
          requires:
            - build_and_test 
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
            - build_and_push_docker_image
          filters:
            branches:
              only: master
