version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.11.0

    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Linter
          command: flake8
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t $DOCKER_IMAGE:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_IMAGE:$TAG
    
  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - run:
          name: init environment variables
          command: |
              heroku config:set SECRET_KEY=$SECRET_KEY SENTRY_DNS=$SENTRY_DNS
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true


workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker_image:
          requires:
            - build_and_test 
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
            - build_and_push_docker_image
          filters:
            branches:
              only: master
