# Generated by Django 3.0 on 2022-11-02 15:31

from django.db import migrations


def migrate_datas(apps, schema_editor):

    try:
        OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        return

    NewProfile = apps.get_model('profiles', 'Profile')
    NewProfile.objects.bulk_create(
        NewProfile(favorite_city=old_object.favorite_city, user_id=old_object.user_id)
        for old_object in OldProfile.objects.all()
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0003_auto_20221102_1519'),

    ]

    operations = [
        migrations.RunPython(migrate_datas),
    ]
