# Generated by Django 3.0 on 2022-11-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20221102_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
